Address Boomi bitbucket PR change requests
pravega/boomi-connector pull request #38
Opened 2020-10-17 00:28 UTC by sabuz-262

2020-10-17 00:30 UTC, sabuz-262 commented on src/main/java/io/pravega/connector/boomi/PravegaWriteOperation.java
Not sure what will do after removing Throwable.

2020-10-20 15:17 UTC, twincitiesguy requested changes

2020-10-23 00:52 UTC, twincitiesguy requested changes

2020-10-23 00:52 UTC, twincitiesguy commented on src/main/java/io/pravega/connector/boomi/PravegaReadOperation.java
> +                    logger.log(Level.WARNING, "Could not close Pravega client", t);
the message should say "could not close pravega client _factory_"

2020-10-27 18:38 UTC, twincitiesguy requested changes

2020-10-27 18:38 UTC, twincitiesguy commented on src/main/java/io/pravega/connector/boomi/PravegaWriteOperation.java
> +            return null;
we should bubble up some kind of exception here - returning null may have unpredictable consequences.  Let's wrap `e` in a RuntimeException and throw that.

2020-10-27 20:22 UTC, twincitiesguy approved these changes

2020-10-27 20:23 UTC, merged